/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class ParkingForm extends javax.swing.JFrame {

    /**
     * Creates new form ParkingForm
     */
    public ParkingForm() {
        initComponents();
        
        loadParkingTransactionsData();
    }

  public void displayParkingTransactions() {
    try {
        dbConnect dbc = new dbConnect();

        String sql = "SELECT pt.transaction_id AS 'Transaction ID', " +
                     "CONCAT(u.u_fname, ' ', u.u_lname) AS 'Employee Name', " +
                     "pt.parking_area AS 'Parking Area', " +
                     "pt.time_in AS 'Time In', pt.time_out AS 'Time Out', " +
                     "pt.duration_hours AS 'Duration (hrs)', " +
                     "pt.rate_per_hour AS 'Rate/Hour', " +
                     "pt.total_fee AS 'Total Fee', " +
                     "pt.status AS 'Status' " +
                     "FROM parking_transactions pt " +
                     "JOIN tbl_accounts u ON pt.u_id = u.u_id";

        ResultSet rs = dbc.getData(sql);

        // Display in JTable
        tblparking.setModel(DbUtils.resultSetToTableModel(rs));

        rs.close();
    } catch (SQLException ex) {
        System.out.println("Error displaying parking transactions: " + ex.getMessage());
    }
}


    DefaultTableModel model = new DefaultTableModel();

public void tableChanged(TableModelEvent e) {
    if (e.getType() == TableModelEvent.UPDATE) {
        int row = e.getFirstRow();
        int column = e.getColumn();

        if (row == -1 || column == -1) return;

        String columnName = model.getColumnName(column);
        if (!columnName.equals("Status")) return;

        updateParkingDatabase(row);
    }
}

private void updateParkingDatabase(int row) {
    try {
        int transactionId = Integer.parseInt(model.getValueAt(row, 0).toString());
        String newStatus = model.getValueAt(row, 8).toString(); // 8 = "Status" column

        String sql = "UPDATE parking_transactions SET status = ? WHERE transaction_id = ?";

        try (Connection conn = new dbConnect().getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, newStatus);
            pst.setInt(2, transactionId);
            pst.executeUpdate();
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}



public void loadParkingTransactionsData() {
    // Set up columns
    String[] columnNames = {
        "Transaction ID", "Employee Name", "Parking Area", "Time In", "Time Out", 
        "Duration (hrs)", "Rate/Hour", "Total Fee", "Status"
    };
    model.setColumnIdentifiers(columnNames);
    model.setRowCount(0);

    String sql = "SELECT pt.transaction_id, CONCAT(u.u_fname, ' ', u.u_lname) AS full_name, " +
                 "pt.parking_area, pt.time_in, pt.time_out, pt.duration_hours, " +
                 "pt.rate_per_hour, pt.total_fee, pt.status " +
                 "FROM parking_transactions pt " +
                 "JOIN tbl_accounts u ON pt.u_id = u.u_id";

    try (Connection con = new dbConnect().getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getInt("transaction_id"),
                rs.getString("full_name"),
                rs.getString("parking_area"),
                rs.getTimestamp("time_in"),
                rs.getTimestamp("time_out"),
                rs.getDouble("duration_hours"),
                rs.getDouble("rate_per_hour"),
                rs.getDouble("total_fee"),
                rs.getString("status")
            });
        }

        tblparking.setModel(model);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblparking = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblparking.setBackground(new java.awt.Color(153, 255, 204));
        tblparking.setForeground(new java.awt.Color(51, 51, 51));
        tblparking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "transaction_id", "u_id", "parking_area", "time_in", "time_out", "duration_hours", "rate_per_hour", "total_fee", "status"
            }
        ));
        jScrollPane1.setViewportView(tblparking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 420));

        jButton1.setText("Select");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 // Check if current user is a Teller
Session sess = Session.getInstance();
if (!"Teller".equalsIgnoreCase(sess.getType())) {
    JOptionPane.showMessageDialog(null, 
        "Only Teller accounts are allowed to perform this action.", 
        "Access Denied", 
        JOptionPane.WARNING_MESSAGE);
    return;
}

// Check if a row is selected in the table
int selectedRow = tblparking.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(null, 
        "Please select a parking transaction to timeout.", 
        "No Selection", 
        JOptionPane.WARNING_MESSAGE);
    return;
}

// Get transaction ID from selected row (assumed to be in column 0)
Object value = tblparking.getValueAt(selectedRow, 0);
int transactionId;

try {
    transactionId = Integer.parseInt(value.toString());
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, 
        "Invalid transaction ID format: " + value, 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
    return;
}

// Update parking transaction status and time_out
try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/parking", "root", "")) {
    String sql = "UPDATE parking_transactions SET status = ?, time_out = NOW() WHERE transaction_id = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, "Timed Out");
    pst.setInt(2, transactionId);

    int affectedRows = pst.executeUpdate();

    if (affectedRows > 0) {
        JOptionPane.showMessageDialog(null, "Parking transaction timed out successfully.");
        loadParkingTransactionsData(); // Refresh table data

        // Open payment form on the EDT
        SwingUtilities.invokeLater(() -> {
            PaymentForm pf = new PaymentForm(transactionId);
            pf.setVisible(true);
        });

    } else {
        JOptionPane.showMessageDialog(null, 
            "Failed to update the parking transaction.", 
            "Update Failed", 
            JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, 
        "Database error: " + ex.getMessage(), 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
}


   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminDashboard AD = new AdminDashboard();
        AD.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblparking;
    // End of variables declaration//GEN-END:variables

    
  
}
