/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import admin.PaymentForm;
import config.Session;
import config.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author milan
 */
public class PaymentForm extends javax.swing.JFrame {

    private int transactionId;
    private int userId;
    private String employeeName;
private String parkingArea;
private String timein;
private String timeout;
private String durationhour;
private String rate;
private String fee;
    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
       this.transactionId = transactionId;
    loadTransactionDetails(transactionId); 
    }

   public PaymentForm(int transactionId) {
        initComponents();
        this.transactionId = transactionId;
        loadTransactionDetails(transactionId);
    }

    
  private void loadTransactionDetails(int transactionId) {
    String sql = "SELECT pt.transaction_id, u.u_fname, u.u_lname, pt.parking_area, pt.time_in, pt.time_out, " +
                 "TIMESTAMPDIFF(HOUR, pt.time_in, pt.time_out) AS duration_hours, pt.rate_per_hour, pt.total_fee " +
                 "FROM parking_transactions pt " +
                 "JOIN tbl_accounts u ON pt.u_id = u.u_id " +  // Changed from 'users' to 'tbl_accounts'
                 "WHERE pt.transaction_id = ?";

    try (Connection conn = new dbConnect().getConnection();
         PreparedStatement pst = conn.prepareStatement(sql)) {

        pst.setInt(1, transactionId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            lblTransactionId.setText(String.valueOf(rs.getInt("transaction_id")));
            lblEmployeeName.setText(rs.getString("u_fname") + " " + rs.getString("u_lname"));
            lblParkingArea.setText(rs.getString("parking_area"));  // Assuming this column exists

            java.sql.Timestamp timeIn = rs.getTimestamp("time_in");
            java.sql.Timestamp timeOut = rs.getTimestamp("time_out");

            lblTimeIn.setText(timeIn != null ? timeIn.toString() : "N/A");
            lblTimeOut.setText(timeOut != null ? timeOut.toString() : "N/A");

            double duration = rs.getDouble("duration_hours");
            if (timeOut == null) {
                lblDuration.setText("Still parked");
            } else {
                lblDuration.setText(String.format("%.2f", duration));
            }

            double rate = rs.getDouble("rate_per_hour");
            lblRate.setText(String.format("%.2f", rate));

            double totalFee = rs.getDouble("total_fee");
            if (totalFee <= 0 && timeOut != null) {
                totalFee = duration * rate;
            }
            lblTotalFee.setText(String.format("%.2f", totalFee));

        } else {
            JOptionPane.showMessageDialog(this, "Transaction details not found.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTransactionId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblParkingArea = new javax.swing.JTextField();
        lblTimeIn = new javax.swing.JLabel();
        lblTimeOut = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDuration = new javax.swing.JTextField();
        lblRate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalFee = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Transaction id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblTransactionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTransactionIdActionPerformed(evt);
            }
        });
        jPanel1.add(lblTransactionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 30));

        jLabel2.setText("Employee Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        jPanel1.add(lblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 30));

        jLabel3.setText("Slot ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel1.add(lblParkingArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 30));

        lblTimeIn.setText("Time In");
        jPanel1.add(lblTimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        lblTimeOut.setText("Time Out");
        jPanel1.add(lblTimeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel4.setText("Duration Hours");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 30));
        jPanel1.add(lblRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, 30));

        jLabel5.setText("Rate");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel6.setText("TOTAL FEE :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        lblTotalFee.setText("FEE");
        jPanel1.add(lblTotalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jButton1.setText("Confirm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 260, 300));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 80, 40));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Print Receipt");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 110, 40));

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTransactionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTransactionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTransactionIdActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
double totalFee = Double.parseDouble(lblTotalFee.getText());
int tellerId = Session.getInstance().getUid(); // Get logged-in user's ID

try (Connection conn = new dbConnect().getConnection()) {
    String sql = "UPDATE parking_transactions SET total_fee = ?, status = ?, teller_id = ? WHERE transaction_id = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setDouble(1, totalFee);
    pst.setString(2, "Paid");
    pst.setInt(3, tellerId);       // Set teller ID
    pst.setInt(4, transactionId);  // transactionId must be initialized beforehand

    int updated = pst.executeUpdate();

    if (updated > 0) {
        JOptionPane.showMessageDialog(this, "Payment completed successfully.");

        // Gather receipt details
        String employeeName = lblEmployeeName.getText();
        String parkingArea = lblParkingArea.getText();
        String durationHour = lblDuration.getText();
        String timeIn = lblTimeIn.getText();
        String timeOut = lblTimeOut.getText();
        String rate = lblRate.getText();
        String fee = lblTotalFee.getText();

        // Build receipt
        StringBuilder receipt = new StringBuilder();
        receipt.append("*********************************************\n");
        receipt.append("*             Parking Ticket Receipt        *\n");
        receipt.append("*********************************************\n\n");
        receipt.append("Date & Time         : ").append(new java.util.Date()).append("\n");
        receipt.append("Transaction ID      : ").append(transactionId).append("\n");
        receipt.append("Employee Name       : ").append(employeeName).append(" (User ID: ").append(tellerId).append(")\n");
        receipt.append("Parking Area        : ").append(parkingArea).append("\n");
        receipt.append("---------------------------------------------\n");
        receipt.append("Duration (Hours)    : ").append(durationHour).append("\n");
        receipt.append("Time In             : ").append(timeIn).append("\n");
        receipt.append("Time Out            : ").append(timeOut).append("\n");
        receipt.append("Rate per Hour       : ").append(rate).append("\n");
        receipt.append("Total Fee           : ").append(fee).append("\n");
        receipt.append("Status              : Paid\n");
        receipt.append("---------------------------------------------\n");
        receipt.append("        Thank you for using our service!     \n");
        receipt.append("*********************************************\n");

        // Show receipt in the text area
        area.setText(receipt.toString());

        // Ask if user wants to close receipt window
        int confirm = JOptionPane.showConfirmDialog(this, "Do you want to close this receipt?", "Close Receipt", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    } else {
        JOptionPane.showMessageDialog(this, "Failed to complete payment.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}



  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // area.setText("");
        //username.setText("");
        //loanamount.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            area.print();
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
                                       
        AdminDashboard ua = new AdminDashboard();
        ua.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lblDuration;
    private javax.swing.JTextField lblEmployeeName;
    private javax.swing.JTextField lblParkingArea;
    private javax.swing.JTextField lblRate;
    private javax.swing.JLabel lblTimeIn;
    private javax.swing.JLabel lblTimeOut;
    private javax.swing.JLabel lblTotalFee;
    private javax.swing.JTextField lblTransactionId;
    // End of variables declaration//GEN-END:variables
}
